//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperAssignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaperAssignment()
        {
            this.Reviews = new HashSet<Review>();
            this.Subreviewers = new HashSet<Subreviewer>();
        }
    
        public int id_paper_assignment { get; set; }
        public int id_paper { get; set; }
        public int id_pcmember { get; set; }
        public System.DateTime date_assigned { get; set; }
        public System.DateTime date_due { get; set; }
        public bool is_delegated { get; set; }
    
        public virtual PCmember PCmember { get; set; }
        public virtual Paper Paper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subreviewer> Subreviewers { get; set; }
    }
}
