//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paper()
        {
            this.PaperAssignments = new HashSet<PaperAssignment>();
        }
    
        public int id_paper { get; set; }
        public string id_conference { get; set; }
        public string title { get; set; }
        public string pdf { get; set; }
        public System.TimeSpan date_submitted { get; set; }
        public bool is_submitted { get; set; }
        public string decision { get; set; }
        public string decision_text { get; set; }
        public System.TimeSpan decision_date { get; set; }
        public string email { get; set; }
        public string author { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaperAssignment> PaperAssignments { get; set; }
        public virtual Author Author { get; set; }
    }
}
