//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Paper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paper()
        {
            this.PaperAssignments = new HashSet<PaperAssignment>();
        }
    
        public int id_paper { get; set; }
        public int id_conference { get; set; }
        [DisplayName("Title")]

        public string title { get; set; }
        [DisplayName("PDF")]

        public string pdf { get; set; }
        [DisplayName("Date submitted")]

        public System.DateTime date_submitted { get; set; }
        [DisplayName("Is submitted")]

        public bool is_submitted { get; set; }
        [DisplayName("Chair's decision")]

        public bool decision { get; set; }
        [DisplayName("Chair's decision text")]

        public string decision_text { get; set; }
        [DisplayName("Chair's decision date")]

        public System.DateTime decision_date { get; set; }
        [DisplayName("Email")]

        public string email { get; set; }
        [DisplayName("Contributions")]

        public string contributions { get; set; }
        [DisplayName("Description")]

        public string text { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaperAssignment> PaperAssignments { get; set; }
        public virtual Author Author { get; set; }
    }
}
