//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class PCmember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PCmember()
        {
            this.PaperAssignments = new HashSet<PaperAssignment>();
        }
    
        public int id_pcmember { get; set; }
        public int id_user { get; set; }
        public int id_conference { get; set; }
        [DisplayName("Is chair")]

        public bool is_chair { get; set; }
        [DisplayName("Date invitation sent")]

        public System.DateTime date_invitation_sent { get; set; }
        [DisplayName("Date invitation accepted")]

        public System.DateTime date_invitation_acc { get; set; }
        [DisplayName("Is valid")]

        public bool is_valid { get; set; }
    
        public virtual User User { get; set; }
        public virtual Conference Conference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaperAssignment> PaperAssignments { get; set; }
    }
}
