//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subreviewer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subreviewer()
        {
            this.Subreviews = new HashSet<Subreview>();
        }
    
        public int id_subreviewer { get; set; }
        public int id_paperassignment { get; set; }
        public int id_user { get; set; }
        public System.DateTime invitation_send_date { get; set; }
        public string invitation_ack { get; set; }
        public bool is_accepted { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subreview> Subreviews { get; set; }
        public virtual PaperAssignment PaperAssignment { get; set; }
    }
}
