//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserModelContainer : DbContext
    {
        public UserModelContainer()
            : base("name=UserModelContainer")
        {
            Users = Set<User>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        internal virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Conference> Conferences { get; set; }
        public virtual DbSet<PCmember> PCmembers { get; set; }
        public virtual DbSet<Paper> Papers { get; set; }
        public virtual DbSet<Subreviewer> Subreviewers { get; set; }
        public virtual DbSet<PaperAssignment> PaperAssignments { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Subreview> Subreviews { get; set; }
    }
}
